In [1]:
import numpy as np

A = np.array([[4, 8],
              [8, 4]])

U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)

print("\nU matrix:")
print(U)

print("\nSingular values:")
print(S)

print("\nSigma matrix:")
Sigma = np.diag(S)
print(Sigma)

print("\nV^T matrix:")
print(VT)

A_reconstructed = U @ Sigma @ VT
print("\nReconstructed A:")
print(A_reconstructed)

Matrix A:
[[4 8]
 [8 4]]

U matrix:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values:
[12.  4.]

Sigma matrix:
[[12.  0.]
 [ 0.  4.]]

V^T matrix:
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]

Reconstructed A:
[[4. 8.]
 [8. 4.]]
